// <auto-generated />
using System;
using ITB.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITB.Application.Dtos.MarcaVeiculoFlatDTO", b =>
                {
                    b.Property<bool>("MarcaAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("marca_ativo");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("MarcaNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca_nome");

                    b.Property<string>("ModeloNome")
                        .HasColumnType("text")
                        .HasColumnName("modelo_nome");

                    b.Property<int?>("VeiculoAno")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_ano");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.Property<string>("VeiculoPlaca")
                        .HasColumnType("text")
                        .HasColumnName("veiculo_placa");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ITB.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("ITB.Domain.Entities.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<int?>("MarcaId1")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id1");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_modelos");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_modelos_marca_id");

                    b.HasIndex("MarcaId1")
                        .HasDatabaseName("ix_modelos_marca_id1");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("ITB.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("perfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("id")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ITB.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<int>("ModeloId")
                        .HasColumnType("integer")
                        .HasColumnName("modelo_id");

                    b.Property<int?>("ModeloId1")
                        .HasColumnType("integer")
                        .HasColumnName("modelo_id1");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .HasColumnName("placa");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("preco");

                    b.Property<uint>("VersaoLinha")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("versao_linha");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_veiculos_marca_id");

                    b.HasIndex("ModeloId")
                        .HasDatabaseName("ix_veiculos_modelo_id");

                    b.HasIndex("ModeloId1")
                        .HasDatabaseName("ix_veiculos_modelo_id1");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ix_veiculos_placa");

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("ITB.Domain.Entities.Modelo", b =>
                {
                    b.HasOne("ITB.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelos_marcas_marca_id");

                    b.HasOne("ITB.Domain.Entities.Marca", null)
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId1")
                        .HasConstraintName("fk_modelos_marcas_marca_id1");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ITB.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("ITB.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_marcas_marca_id");

                    b.HasOne("ITB.Domain.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_modelos_modelo_id");

                    b.HasOne("ITB.Domain.Entities.Modelo", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("ModeloId1")
                        .HasConstraintName("fk_veiculos_modelos_modelo_id1");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("ITB.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ITB.Domain.Entities.Modelo", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
